/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0/userguide/building_java_projects.html
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.13.5")

    // These dependencies are used by the application.
    implementation("org.typelevel:cats-core_2.13:2.4.2")
    implementation("org.typelevel:cats-effect_2.13:2.3.1")
    implementation("org.creativescala:doodle_2.13:0.9.23")

    // Use Munit for testing our library
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.scalameta:munit_2.13:0.7.22")
}

application {
    // Define the main class for the application.
    mainClass.set("section1.Composition")
}
